/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-05 12:14:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lec.beans.*;

public final class reserve_005fmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604305648486L));
    _jspx_dependants.put("jar:file:/C:/Users/gbdld/Dropbox/JB10/SemiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SemiProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.lec.beans");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 예약-수정-페이지, 김지민 -->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 // Controller 로부터 결과 데이터 받음
	String c_num = (String)session.getAttribute("c_num");
	PetDTO[] parr = (PetDTO [])request.getAttribute("plist");
	ReservationDTO [] rarr = (ReservationDTO [])request.getAttribute("rlist");

	String [] res_info ={"아카데미","독파크","메디컬센터","유치원","그루밍","스페셜케어","호텔,데이케어"};

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/reservation.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b95da9d126.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>예약수정 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 정호 10/30 수정 -->\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- 컨텐츠A -->\r\n");
      out.write("\t<section class=\"conA\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h4 id=\"start\">어떤 서비스를 받아야 할 지 고민이신가요?</h4>\r\n");
      out.write("\t\t\t<h3 id=\"start\">상담 신청해 주시면 영업일 기준 1~2일 이내로 전화 드립니다.</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 컨텐츠B -->\r\n");
      out.write("\t<section class=\"conB\">\r\n");
      out.write("\t\t<div class=\"container2\">\r\n");
      out.write("\t\t\t<!-- 좌측 -->\r\n");
      out.write("\t\t\t<div class=\"menu1\">\r\n");
      out.write("\t\t\t\t<div id=\"tel\">\r\n");
      out.write("\t                <h3>호텔 왈왈 역삼역 캠퍼스</h3>\r\n");
      out.write("\t                <br>\r\n");
      out.write("\t                <p>02-1234-1234<p>\r\n");
      out.write("           \t\t </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"time\">\r\n");
      out.write("\t\t            <h3>예약 및 상담 시간</h3>\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t                <p>08:00 ~ 20:00<p>\r\n");
      out.write("           \t\t </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"friend\">\r\n");
      out.write("\t                <h3>플러스 친구</h3>\r\n");
      out.write("\t                <br>\r\n");
      out.write("\t                <p>[왈왈호텔]로 검색<p>\r\n");
      out.write("           \t\t </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"announce\">\r\n");
      out.write("\t                <h3>안내사항</h3>\r\n");
      out.write("\t                <br>\r\n");
      out.write("\t                <p>왈왈호텔 이용 시 주의사항<p>\r\n");
      out.write("           \t\t </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br><br><br><br><br>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t1년 이내 5가지 접종(종합, 코로나, 켄넬코프, 신종 인플루엔자, 광견병) 받지 않은 반려견은 입실이 제한됩니다.\r\n");
      out.write("\t\t\t\t\t\t\t* 접종기록은 접종병원명이 꼭 필요하므로 증빙 자료는 미리 준비해주세요\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t1살 미만의 반려견인 경우 항체 검사가 필수 입니다.\r\n");
      out.write("\t\t\t\t\t\t\t(단, 1살 이상 시 재접종 기록 확인)\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t생리,건강문제 또는 공격성이 강해 타 고객의 이용에 피해가 되는 반려견 일 경우 입실이 제한됩니다.\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 우측 -->        \r\n");
      out.write("        \t<div class=\"menu2\">\r\n");
      out.write("        \t\t<form name=\"rform\" action=\"modifyOk.do?num=");
      out.print(rarr[0].getRes_num() );
      out.write("\" method=\"post\" onsubmit=\"return chkDate()\">\r\n");
      out.write("\t\t\t\t\t반려견 선택하기:<br>\r\n");
      out.write("\t\t\t\t\t<select name=\"select_pet\"> \r\n");
      out.write("\t\t\t\t\t<!-- select_pet에 value값이 담겨서 간다. -->\t\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print( rarr[0].getPet_num() );
      out.write("\" selected>");
      out.print(parr[0].getPet_name() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\t희망서비스:<br>\r\n");
      out.write("\t\t\t\t\t<select name=res_sinfo>\r\n");
      out.write("\t\t\t\t\t");

						for(int i=0; i<res_info.length;i++){
							if(res_info[i].equals(rarr[0].getRes_sinfo())){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(res_info[i] );
      out.write("\" selected>");
      out.print(res_info[i] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

							}else{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(res_info[i] );
      out.write('"');
      out.write('>');
      out.print(res_info[i] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");
 			
							}
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\t체크인:<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"res_startdate\" id=\"startdate\" value=\"");
      out.print(rarr[0].getRes_startdate() );
      out.write("\" min=\"\" max=\"\";><br><br><br>\r\n");
      out.write("\t\t\t\t\t체크아웃:<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"res_lastdate\" id=\"lastdate\" value=\"");
      out.print(rarr[0].getRes_lastdate() );
      out.write("\" min=\"\" max=\"\";><br><br><br>\r\n");
      out.write("\t\t\t\t\t기타(요청사항):<br>\r\n");
      out.write("\t\t\t\t\t<textarea placeholder=\"효과적인 서비스를 위해 중성화 여부, 문제행동 등 자세한 사항을 적어주세요.\" name=\"res_message\" cols=\"30\" rows=\"10\" >");
      out.print(rarr[0].getRes_message() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t<br><br>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"s_button\" value=\"수정하기\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \r\n");
      out.write("        </div>   \r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- 푸터 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- 정호 : 10/30 -->\r\n");
      out.write("<script src=\"JS/index.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"JS/reserve_modify.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
