/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-12 03:02:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604305648486L));
    _jspx_dependants.put("jar:file:/C:/Users/gbdld/Dropbox/JB10/SemiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SemiProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 이호인 리뷰 화면   -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/write.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b95da9d126.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<title>왈왈 호텔</title>\r\n");
      out.write("<script src=\"ckeditor/ckeditor.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\t<!-- 호인 11/02 include -->\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"JS/write.js\"></script>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<section class=\"conA\">\r\n");
      out.write("\t\t<div class=\"containerA\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<h1>Writing</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section class=\"conB\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t<form name=\"frm\" action=\"writeOk.do\" method=\"post\" onsubmit=\"return chkSubmit()\"><br>\r\n");
      out.write("\t\t<!--  작성자:-->\r\n");
      out.write("\t\t<!-- <input type=\"text\" name=\"name\"/><br>-->\r\n");
      out.write("\t\t제목:\r\n");
      out.write("\t\t<input type=\"text\" name=\"subject\"/><br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t평점:<br>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"star\" value=\"1\">★☆☆☆☆<br>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"star\" value=\"2\">★★☆☆☆<br>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"star\" value=\"3\">★★★☆☆<br>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"star\" value=\"4\">★★★★☆<br>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"star\" value=\"5\">★★★★★<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t내용:<br>\r\n");
      out.write("\t\t<textarea name=\"content\" id=\"editor1\"></textarea>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tCKEDITOR.replace('editor1', {\r\n");
      out.write("\t\t\tallowedContent: true,    // HTML 태그 자동 삭제 방지 설정\r\n");
      out.write("\t\t\twidth: '100%px',       //  최초 너비, 높이 지정 가능\r\n");
      out.write("\t\t\theight: '400px',\r\n");
      out.write("\t\t\tfilebrowserUploadUrl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fileUpload.do'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\t\r\n");
      out.write("\t\t");

		String name;
		int a;
		if(session.getAttribute("c_num") != null){
			name = (String)session.getAttribute("c_num");
			a = Integer.parseInt(name);
		}else{
			name = null;
			a = 0;
		}
	
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" name=\"c_num\" value=\"");
      out.print( a );
      out.write("\"><br>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<input type=\"submit\" class=\"akk\" value=\"등록하기\"/>\r\n");
      out.write("\t\t<div class=\"containerG\">\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"location.href='review.do?page=1'\">목록으로</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<section class=\"btnA\">\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- 푸터 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
